spring.ai.ollama.init.pull-model-strategy=WHEN_MISSING
spring.ai.ollama.init.embedding.additional-models[0]=mxbai-embed-large
#spring.ai.ollama.init.embedding.additional-models[1]=llama3.2:1b
spring.ai.ollama.init.timeout=15m
spring.ai.ollama.chat.model=mistral
spring.ai.ollama.chat.keep-alive=30m
spring.ai.ollama.chat.temperature=0.2
spring.ai.ollama.chat.top-k=2
spring.ai.ollama.chat.top-p=0.2
