daily-nav.database-type=postgres
daily-nav.url=${DAILY_NAV_URL:jdbc:postgresql://postgres:5432/dailynav}
daily-nav.username=${DAILY_NAV_USERNAME:postgres}
daily-nav.password=${DAILY_NAV_PASSWORD:postgres}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
