daily-nav.database-type=postgres
daily-nav.url=${DAILY_NAV_URL:jdbc:postgresql://postgres:5432/dailynav}
daily-nav.username=${DAILY_NAV_USERNAME:postgres}
daily-nav.password=${DAILY_NAV_PASSWORD:postgres}

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.datasource.url=${daily-nav.url}
spring.datasource.username=${daily-nav.username}
spring.datasource.password=${daily-nav.password}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
